### ISSUE TITLE
It doesn't follow 301 redirect?

### ISSUE THREAD

**Issue by dexcell** [Tjatse/req-fast#1]
Hi, thanks for all of your works, many of your library is helpful.

I just tried req-fast but it's do not follow permanent redirect (301).
Is this expected behaviors?
````
var req = require('req-fast');
req({
    url: 'http://dentistvschef.wordpress.com/2013/01/16/japanese-spring-onionscallionleek-pancake-ala-dentist-chef/'
}, function(err, res){
    console.log(res.body);
});
````

Thanks

**Comment by Tjatse** [comment]
You're welcome!

Actually, it follows 301 redirect, in order to improve performance, the `http` or `https` client is initialized before any request, so, you'd better not to change protocol during your request (**this should be enhanced**), e.g.:
When you're visiting `http://dentistvschef.wordpress.com/2013/01/16/japanese-spring-onionscallionleek-pancake-ala-dentist-chef/`, it's being redirected to `https://dentistvschef.wordpress.com/2013/01/16/japanese-spring-onionscallionleek-pancake-ala-dentist-chef/`, and the client is still [http](https://nodejs.org/api/http.html) but not [https](https://nodejs.org/api/https.html).

The following code goes fine.
```javascript
var req = require('req-fast');
req({
    url: 'https://dentistvschef.wordpress.com/2013/01/16/japanese-spring-onionscallionleek-pancake-ala-dentist-chef/'
}, function(err, res){
    console.log(res.body);
});
```

**Comment by dexcell** [comment]
Hi @Tjatse ,
Thank you for your fast reply and clear explanation.

Currently my problem is i cannot change the url manually to `https` as it generated automatically.

Here is my situation:
1. I crawl page and extract url links from there.
2. Then i pass the url link to `node-art` (which is awesome :+1: ), but then `req-fast` failed to follow 301 redirect with protocol change from `http` to `https`, which result in wrong `art.content`.

So, looking at my situation, is the best option for me is now wait until this `req-fast` lib is enhanced?

By the way, is it possible to skip non `200` status code using `node-art`? 
(Just asking, if possible then probably i would skip insert `art.content` for those url that return != 200)

Thank you

**Comment by Tjatse** [comment]
Hi, @dexcell Just try the latest `req-fast` / `read-art`, these issues should be fixed.

**Comment by dexcell** [comment]
You are amazing! :beer:
